### ISSUE TITLE
Testlights doesn't return

### ISSUE THREAD

**Issue by Dennis802** [nganzalo/Hue_Implementation#4]
All set up, API key was made, IP was entered, pressed connect but !Testlights doesn't return anything at all. Is it supposed to give an error if it isn't set up or is it safe to say it isn't set up right at all? Thanks!

**Comment by Nick-Anzalone** [comment]
> All set up, API key was made, IP was entered, pressed connect but !Testlights doesn't return anything at all. Is it supposed to give an error if it isn't set up or is it safe to say it isn't set up right at all? Thanks!

Hey sorry about that, try the command "::testlights" instead. I forgot to update the README.md with the last update. Sorry about that.
